spring:
  application:
    name: banking
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username:  postgres
    password:  postgres

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd
jwt:
  secret: 7A25432A462D4A614E645267556B58703273357638792F423F4528482B4B6250
  expiration: 86400000
